name: Deploy on GCP

on:
  push:
    branches: [ main ]

env:
  FLASK_APP: ${{ secrets.FLASK_APP }}
  FLASK_ENV: ${{ secrets.FLASK_ENV }}
  FLASK_DEBUG: ${{ secrets.FLASK_DEBUG }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  MONGO_URI: ${{ secrets.MONGO_URI }}
  MONGO_DATABASE: ${{ secrets.MONGO_DATABASE }}
  GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
  OAUTHLIB_INSECURE_TRANSPORT: ${{ secrets.OAUTHLIB_INSECURE_TRANSPORT }}
  FRONTEND_URL: ${{ secrets.FRONTEND_URL }}
  BACKEND_URL: ${{ secrets.BACKEND_URL }}
  FLASK_RUN_PORT: ${{ secrets.FLASK_RUN_PORT }}
  FLASK_RUN_HOST: ${{ secrets.FLASK_RUN_HOST }}
  PORT: ${{ secrets.FLASK_RUN_PORT }}


jobs:

  deploy:

    name: "Config GCP"
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: gcr.io/${{ secrets.GCP_PROJECT_ID }}/labinventory:latest
      DOCKER_DEFAULT_PLATFORM: linux/amd64

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3

      - name: GCP Auth
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Docker Build Image
        run: DOCKER_DEFAULT_PLATFORM=linux/amd64 docker build -t $IMAGE_NAME .
      
      - name: Push Docker Image
        run: docker push $IMAGE_NAME
      
      - name : Deploy Docker Image
        run: gcloud run deploy labinventory-backend --image $IMAGE_NAME --region us-central1 --allow-unauthenticated --platform managed --port 8080 --update-env-vars "FLASK_APP=app.py,FLASK_ENV=development,FLASK_DEBUG=True,SECRET_KEY=${{ secrets.SECRET_KEY }},MONGO_DATABASE=${{ secrets.MONGO_DATABASE }},OAUTHLIB_INSECURE_TRANSPORT=1,FRONTEND_URL=${{ secrets.FRONTEND_URL }},BACKEND_URL=${{ secrets.BACKEND_URL }},FLASK_RUN_PORT=8080,FLASK_RUN_HOST=0.0.0.0"
