name: LABinventary

on:
  push:
    branches: [ main, dev ]

jobs:

  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9.15 ]

    steps:

    - uses: actions/checkout@master

    - name: Initialize Python 
      uses: actions/setup-python@v1
      with:
        python-version: ${{matrix.python-version}}

    - name: Install/update pip
      run: |
        python -m pip install --upgrade pip
    
    - name: Create and start virtual environment
      run: |
        python3 -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        pip install -r requirements.txt  

    - name: Run unit tests with coverage report
      run: |
        pytest tests/ -v -W ignore::DeprecationWarning --cov


  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: [ 3.9.15 ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/devinventary-backend:latest
